export const CATEGORY_THEMES = {
  shortVowels: { color: '#FF006E', glow: 'rgba(255,0,110,0.35)',  dim: 'rgba(255,0,110,0.13)',  label: 'Short Vowels', icon: '🔴', nebula: '#FF006E' },
  longVowels:  { color: '#00F5D4', glow: 'rgba(0,245,212,0.35)',  dim: 'rgba(0,245,212,0.13)',  label: 'Long Vowels',  icon: '🟢', nebula: '#00F5D4' },
  consonants:  { color: '#BE00FF', glow: 'rgba(190,0,255,0.35)',  dim: 'rgba(190,0,255,0.13)',  label: 'Consonants',   icon: '🟣', nebula: '#BE00FF' },
  digraphs:    { color: '#FF7300', glow: 'rgba(255,115,0,0.35)',  dim: 'rgba(255,115,0,0.13)',  label: 'Digraphs',     icon: '🟠', nebula: '#FF7300' },
  blends:      { color: '#00FF88', glow: 'rgba(0,255,136,0.35)',  dim: 'rgba(0,255,136,0.13)',  label: 'Blends',       icon: '🟡', nebula: '#00FF88' },
  vowelTeams:  { color: '#4D79FF', glow: 'rgba(77,121,255,0.35)', dim: 'rgba(77,121,255,0.13)', label: 'Vowel Teams',  icon: '🔵', nebula: '#4D79FF' },
  rControlled: { color: '#FF4571', glow: 'rgba(255,69,113,0.35)', dim: 'rgba(255,69,113,0.13)', label: 'R-Controlled', icon: '🩷', nebula: '#FF4571' },
  wordEndings: { color: '#FFD700', glow: 'rgba(255,215,0,0.35)',  dim: 'rgba(255,215,0,0.13)',  label: 'Word Endings', icon: '✨', nebula: '#FFD700' },
};

export const SOUNDS = {
  shortVowels: [
    { id:'sa',  letters:'a',  symbol:'/æ/',  emoji:'🍎', example:'apple',    words:['apple','ant','axe'],     speech:'aah, aah, apple, ant, axe' },
    { id:'se',  letters:'e',  symbol:'/ɛ/',  emoji:'🥚', example:'egg',      words:['egg','end','elf'],       speech:'eh, eh, egg, end, elf' },
    { id:'si',  letters:'i',  symbol:'/ɪ/',  emoji:'🧊', example:'igloo',    words:['igloo','inch','if'],     speech:'ih, ih, igloo, inch, if' },
    { id:'so',  letters:'o',  symbol:'/ɒ/',  emoji:'🐙', example:'octopus',  words:['octopus','odd','ox'],    speech:'aw, aw, octopus, odd, ox' },
    { id:'su',  letters:'u',  symbol:'/ʌ/',  emoji:'☂️', example:'umbrella', words:['umbrella','up','under'], speech:'uh, uh, umbrella, up, under' },
  ],
  longVowels: [
    { id:'la',  letters:'ā',  symbol:'/eɪ/', emoji:'🎂', example:'cake',     words:['cake','name','gate'],    speech:'ay, ay, cake, name, gate' },
    { id:'le',  letters:'ē',  symbol:'/iː/', emoji:'🐍', example:'eel',      words:['eel','eat','eve'],       speech:'ee, ee, eel, eat, eve' },
    { id:'li',  letters:'ī',  symbol:'/aɪ/', emoji:'❄️', example:'ice',      words:['ice','ivy','isle'],      speech:'eye, eye, ice, ivy, isle' },
    { id:'lo',  letters:'ō',  symbol:'/oʊ/', emoji:'🚪', example:'open',     words:['open','oak','over'],     speech:'oh, oh, open, oak, over' },
    { id:'lu',  letters:'ū',  symbol:'/juː/',emoji:'🦄', example:'unicorn',  words:['unicorn','use','unit'],  speech:'yoo, yoo, unicorn, use, unit' },
  ],
  consonants: [
    { id:'cb',  letters:'b',  symbol:'/b/',  emoji:'⚽', example:'ball',     words:['ball','bat','bug'],      speech:'buh, buh, ball, bat, bug' },
    { id:'cc',  letters:'c',  symbol:'/k/',  emoji:'🐱', example:'cat',      words:['cat','cup','cap'],       speech:'kuh, kuh, cat, cup, cap' },
    { id:'ccs', letters:'c',  symbol:'/s/',  emoji:'🏙️', example:'city',     words:['city','cent','cycle'],   speech:'sss, sss, city, cent, cycle' },
    { id:'cd',  letters:'d',  symbol:'/d/',  emoji:'🐶', example:'dog',      words:['dog','den','dip'],       speech:'duh, duh, dog, den, dip' },
    { id:'cf',  letters:'f',  symbol:'/f/',  emoji:'🐟', example:'fish',     words:['fish','fun','fog'],      speech:'fff, fff, fish, fun, fog' },
    { id:'cg',  letters:'g',  symbol:'/ɡ/',  emoji:'🐐', example:'goat',     words:['goat','gap','got'],      speech:'guh, guh, goat, gap, got' },
    { id:'cgj', letters:'g',  symbol:'/dʒ/', emoji:'💎', example:'gem',      words:['gem','gel','gist'],      speech:'juh, juh, gem, gel, gist' },
    { id:'ch',  letters:'h',  symbol:'/h/',  emoji:'🎩', example:'hat',      words:['hat','hop','hen'],       speech:'huh, huh, hat, hop, hen' },
    { id:'cj',  letters:'j',  symbol:'/dʒ/', emoji:'🎯', example:'jump',     words:['jump','jam','jet'],      speech:'juh, juh, jump, jam, jet' },
    { id:'ck',  letters:'k',  symbol:'/k/',  emoji:'🪁', example:'kite',     words:['kite','kit','key'],      speech:'kuh, kuh, kite, kit, key' },
    { id:'cl',  letters:'l',  symbol:'/l/',  emoji:'🦁', example:'lion',     words:['lion','lip','log'],      speech:'lll, lll, lion, lip, log' },
    { id:'cm',  letters:'m',  symbol:'/m/',  emoji:'🌙', example:'moon',     words:['moon','map','mat'],      speech:'mmm, mmm, moon, map, mat' },
    { id:'cn',  letters:'n',  symbol:'/n/',  emoji:'👃', example:'nose',     words:['nose','nap','net'],      speech:'nnn, nnn, nose, nap, net' },
    { id:'cp',  letters:'p',  symbol:'/p/',  emoji:'🐷', example:'pig',      words:['pig','pan','pet'],       speech:'puh, puh, pig, pan, pet' },
    { id:'cq',  letters:'qu', symbol:'/kw/', emoji:'👑', example:'queen',    words:['queen','quick','quit'],  speech:'kwuh, kwuh, queen, quick, quit' },
    { id:'cr',  letters:'r',  symbol:'/r/',  emoji:'🐰', example:'rabbit',   words:['rabbit','run','rap'],    speech:'rrr, rrr, rabbit, run, rap' },
    { id:'css', letters:'s',  symbol:'/s/',  emoji:'☀️', example:'sun',      words:['sun','sap','set'],       speech:'sss, sss, sun, sap, set' },
    { id:'ct',  letters:'t',  symbol:'/t/',  emoji:'🐯', example:'tiger',    words:['tiger','tap','ten'],     speech:'tuh, tuh, tiger, tap, ten' },
    { id:'cv',  letters:'v',  symbol:'/v/',  emoji:'🚐', example:'van',      words:['van','vat','vow'],       speech:'vvv, vvv, van, vat, vow' },
    { id:'cw',  letters:'w',  symbol:'/w/',  emoji:'🐺', example:'wolf',     words:['wolf','wet','win'],      speech:'wuh, wuh, wolf, wet, win' },
    { id:'cx',  letters:'x',  symbol:'/ks/', emoji:'🦊', example:'fox',      words:['fox','six','box'],       speech:'ks, ks, fox, six, box' },
    { id:'cy',  letters:'y',  symbol:'/j/',  emoji:'🐃', example:'yak',      words:['yak','yes','yet'],       speech:'yuh, yuh, yak, yes, yet' },
    { id:'cz',  letters:'z',  symbol:'/z/',  emoji:'🦓', example:'zebra',    words:['zebra','zip','zap'],     speech:'zzz, zzz, zebra, zip, zap' },
  ],
  digraphs: [
    { id:'dch', letters:'ch', symbol:'/tʃ/', emoji:'🪑', example:'chair',   words:['chair','chip','chop'],   speech:'ch, ch, chair, chip, chop' },
    { id:'dsh', letters:'sh', symbol:'/ʃ/',  emoji:'🚢', example:'ship',    words:['ship','shop','show'],    speech:'shh, shh, ship, shop, show' },
    { id:'dthv',letters:'th', symbol:'/ð/',  emoji:'📖', example:'the',     words:['the','then','them'],     speech:'th, th, the, then, them' },
    { id:'dthu',letters:'th', symbol:'/θ/',  emoji:'💭', example:'think',   words:['think','thin','thick'],  speech:'th, th, think, thin, thick' },
    { id:'dwh', letters:'wh', symbol:'/w/',  emoji:'🎡', example:'wheel',   words:['wheel','when','whip'],   speech:'wh, wh, wheel, when, whip' },
    { id:'dph', letters:'ph', symbol:'/f/',  emoji:'📱', example:'phone',   words:['phone','photo','graph'], speech:'fff, fff, phone, photo, graph' },
    { id:'dgh', letters:'gh', symbol:'/f/',  emoji:'😂', example:'laugh',   words:['laugh','rough','tough'], speech:'fff, fff, laugh, rough, tough' },
    { id:'dck', letters:'ck', symbol:'/k/',  emoji:'🦆', example:'duck',    words:['duck','back','neck'],    speech:'kuh, kuh, duck, back, neck' },
    { id:'dng', letters:'ng', symbol:'/ŋ/',  emoji:'💍', example:'ring',    words:['ring','sing','long'],    speech:'ng, ng, ring, sing, long' },
    { id:'dkn', letters:'kn', symbol:'/n/',  emoji:'🦵', example:'knee',    words:['knee','knot','know'],    speech:'nnn, nnn, knee, knot, know' },
    { id:'dwr', letters:'wr', symbol:'/r/',  emoji:'✍️', example:'write',   words:['write','wrap','wren'],   speech:'rrr, rrr, write, wrap, wren' },
  ],
  blends: [
    { id:'bbl', letters:'bl', symbol:'/bl/', emoji:'💙', example:'blue',    words:['blue','black','blow'],   speech:'bl, bl, blue, black, blow' },
    { id:'bcl', letters:'cl', symbol:'/kl/', emoji:'🕐', example:'clock',   words:['clock','clay','clap'],   speech:'cl, cl, clock, clay, clap' },
    { id:'bfl', letters:'fl', symbol:'/fl/', emoji:'🚩', example:'flag',    words:['flag','flat','fly'],     speech:'fl, fl, flag, flat, fly' },
    { id:'bgl', letters:'gl', symbol:'/ɡl/', emoji:'🌍', example:'globe',   words:['globe','glad','glow'],   speech:'gl, gl, globe, glad, glow' },
    { id:'bpl', letters:'pl', symbol:'/pl/', emoji:'🎮', example:'play',    words:['play','plan','plop'],    speech:'pl, pl, play, plan, plop' },
    { id:'bsl', letters:'sl', symbol:'/sl/', emoji:'🛝', example:'slide',   words:['slide','slim','slap'],   speech:'sl, sl, slide, slim, slap' },
    { id:'bbr', letters:'br', symbol:'/br/', emoji:'🍞', example:'bread',   words:['bread','brim','brag'],   speech:'br, br, bread, brim, brag' },
    { id:'bcr', letters:'cr', symbol:'/kr/', emoji:'🦀', example:'crab',    words:['crab','crop','crew'],    speech:'cr, cr, crab, crop, crew' },
    { id:'bdr', letters:'dr', symbol:'/dr/', emoji:'🥁', example:'drum',    words:['drum','drip','drop'],    speech:'dr, dr, drum, drip, drop' },
    { id:'bfr', letters:'fr', symbol:'/fr/', emoji:'🐸', example:'frog',    words:['frog','free','from'],    speech:'fr, fr, frog, free, from' },
    { id:'bgr', letters:'gr', symbol:'/ɡr/', emoji:'🍇', example:'grape',   words:['grape','grip','grow'],   speech:'gr, gr, grape, grip, grow' },
    { id:'bpr', letters:'pr', symbol:'/pr/', emoji:'🤴', example:'prince',  words:['prince','prod','prop'],  speech:'pr, pr, prince, prod, prop' },
    { id:'btr', letters:'tr', symbol:'/tr/', emoji:'🌳', example:'tree',    words:['tree','trip','trap'],    speech:'tr, tr, tree, trip, trap' },
    { id:'bsc', letters:'sc', symbol:'/sk/', emoji:'🧣', example:'scarf',   words:['scarf','scan','score'],  speech:'sc, sc, scarf, scan, score' },
    { id:'bsk', letters:'sk', symbol:'/sk/', emoji:'⛸️', example:'skate',   words:['skate','skip','sky'],    speech:'sk, sk, skate, skip, sky' },
    { id:'bsm', letters:'sm', symbol:'/sm/', emoji:'😊', example:'smile',   words:['smile','smack','smoke'], speech:'sm, sm, smile, smack, smoke' },
    { id:'bsn', letters:'sn', symbol:'/sn/', emoji:'🐍', example:'snake',   words:['snake','snap','snip'],   speech:'sn, sn, snake, snap, snip' },
    { id:'bsp', letters:'sp', symbol:'/sp/', emoji:'🕷️', example:'spider',  words:['spider','spin','spot'],  speech:'sp, sp, spider, spin, spot' },
    { id:'bst', letters:'st', symbol:'/st/', emoji:'⭐', example:'star',    words:['star','stop','stem'],    speech:'st, st, star, stop, stem' },
    { id:'bsw', letters:'sw', symbol:'/sw/', emoji:'🦢', example:'swan',    words:['swan','swim','swap'],    speech:'sw, sw, swan, swim, swap' },
    { id:'bstr',letters:'str',symbol:'/str/',emoji:'🎻', example:'string',  words:['string','strip','stride'],speech:'str, str, string, strip, stride' },
    { id:'bspr',letters:'spr',symbol:'/spr/',emoji:'🌸', example:'spring',  words:['spring','spray','sprint'],speech:'spr, spr, spring, spray, sprint' },
    { id:'bscr',letters:'scr',symbol:'/skr/',emoji:'😱', example:'scream',  words:['scream','scrub','scroll'],speech:'scr, scr, scream, scrub, scroll' },
    { id:'bspl',letters:'spl',symbol:'/spl/',emoji:'💦', example:'splash',  words:['splash','split','splat'], speech:'spl, spl, splash, split, splat' },
    { id:'bsqu',letters:'squ',symbol:'/skw/',emoji:'🟥', example:'square',  words:['square','squid','squeak'],speech:'squ, squ, square, squid, squeak' },
    { id:'bthr',letters:'thr',symbol:'/θr/', emoji:'3️⃣', example:'three',  words:['three','throw','throne'], speech:'thr, thr, three, throw, throne' },
  ],
  vowelTeams: [
    { id:'vai',  letters:'ai', symbol:'/eɪ/', emoji:'🌧️', example:'rain',  words:['rain','mail','tail'],    speech:'ay, ay, rain, mail, tail' },
    { id:'vay',  letters:'ay', symbol:'/eɪ/', emoji:'🎮', example:'play',  words:['play','day','say'],      speech:'ay, ay, play, day, say' },
    { id:'vea',  letters:'ea', symbol:'/iː/', emoji:'🍽️', example:'eat',   words:['eat','seal','beam'],     speech:'ee, ee, eat, seal, beam' },
    { id:'vee',  letters:'ee', symbol:'/iː/', emoji:'🌳', example:'tree',  words:['tree','see','bee'],      speech:'ee, ee, tree, see, bee' },
    { id:'vie',  letters:'ie', symbol:'/aɪ/', emoji:'🥧', example:'pie',   words:['pie','tie','die'],       speech:'eye, eye, pie, tie, die' },
    { id:'voa',  letters:'oa', symbol:'/oʊ/', emoji:'⛵', example:'boat',  words:['boat','road','coat'],    speech:'oh, oh, boat, road, coat' },
    { id:'voe',  letters:'oe', symbol:'/oʊ/', emoji:'🦶', example:'toe',   words:['toe','hoe','doe'],       speech:'oh, oh, toe, hoe, doe' },
    { id:'vool', letters:'oo', symbol:'/uː/', emoji:'🌙', example:'moon',  words:['moon','pool','cool'],    speech:'oo, oo, moon, pool, cool' },
    { id:'voos', letters:'oo', symbol:'/ʊ/',  emoji:'📚', example:'book',  words:['book','look','cook'],    speech:'oo short, oo short, book, look, cook' },
    { id:'vou',  letters:'ou', symbol:'/aʊ/', emoji:'☁️', example:'cloud', words:['cloud','out','loud'],    speech:'ow, ow, cloud, out, loud' },
    { id:'vowd', letters:'ow', symbol:'/aʊ/', emoji:'🐄', example:'cow',   words:['cow','how','now'],       speech:'ow, ow, cow, how, now' },
    { id:'vowl', letters:'ow', symbol:'/oʊ/', emoji:'❄️', example:'snow',  words:['snow','grow','show'],    speech:'oh, oh, snow, grow, show' },
    { id:'voi',  letters:'oi', symbol:'/ɔɪ/', emoji:'🪙', example:'coin',  words:['coin','oil','foil'],     speech:'oy, oy, coin, oil, foil' },
    { id:'voy',  letters:'oy', symbol:'/ɔɪ/', emoji:'👦', example:'boy',   words:['boy','joy','toy'],       speech:'oy, oy, boy, joy, toy' },
    { id:'vau',  letters:'au', symbol:'/ɔː/', emoji:'🏋️', example:'haul',  words:['haul','haunt','fault'],  speech:'aw, aw, haul, haunt, fault' },
    { id:'vaw',  letters:'aw', symbol:'/ɔː/', emoji:'🪚', example:'saw',   words:['saw','claw','draw'],     speech:'aw, aw, saw, claw, draw' },
    { id:'vew',  letters:'ew', symbol:'/juː/',emoji:'✨', example:'new',   words:['new','dew','grew'],      speech:'yoo, yoo, new, dew, grew' },
    { id:'vue',  letters:'ue', symbol:'/uː/', emoji:'💙', example:'blue',  words:['blue','glue','true'],    speech:'oo, oo, blue, glue, true' },
    { id:'vui',  letters:'ui', symbol:'/uː/', emoji:'🍓', example:'fruit', words:['fruit','suit','juice'],  speech:'oo, oo, fruit, suit, juice' },
  ],
  rControlled: [
    { id:'rar',  letters:'ar', symbol:'/ɑːr/', emoji:'🚗', example:'car',  words:['car','star','bar'],      speech:'ar, ar, car, star, bar' },
    { id:'rer',  letters:'er', symbol:'/ɜːr/', emoji:'👩', example:'her',  words:['her','fern','stern'],    speech:'er, er, her, fern, stern' },
    { id:'rir',  letters:'ir', symbol:'/ɜːr/', emoji:'🐦', example:'bird', words:['bird','girl','first'],   speech:'er, er, bird, girl, first' },
    { id:'ror',  letters:'or', symbol:'/ɔːr/', emoji:'🌽', example:'corn', words:['corn','born','horse'],   speech:'or, or, corn, born, horse' },
    { id:'rur',  letters:'ur', symbol:'/ɜːr/', emoji:'🔥', example:'burn', words:['burn','turn','curl'],    speech:'er, er, burn, turn, curl' },
  ],
  wordEndings: [
    { id:'wedge', letters:'dge',  symbol:'/dʒ/',  emoji:'🌉', example:'bridge',  words:['bridge','fudge','badge'],    speech:'juh, juh, bridge, fudge, badge' },
    { id:'wetion',letters:'tion', symbol:'/ʃən/', emoji:'🌍', example:'nation',  words:['nation','action','station'], speech:'shun, shun, nation, action, station' },
    { id:'weal',  letters:'-al',  symbol:'/əl/',  emoji:'⚽', example:'ball',    words:['ball','call','hall'],         speech:'ul, ul, ball, call, hall' },
    { id:'wele',  letters:'-le',  symbol:'/əl/',  emoji:'🕯️', example:'table',   words:['table','bottle','purple'],   speech:'ul, ul, table, bottle, purple' },
    { id:'weus',  letters:'-us',  symbol:'/əs/',  emoji:'🚌', example:'bus',     words:['bus','plus','cactus'],        speech:'us, us, bus, plus, cactus' },
    { id:'weing', letters:'-ing', symbol:'/ɪŋ/',  emoji:'🎵', example:'sing',    words:['sing','ring','bring'],        speech:'ing, ing, sing, ring, bring' },
    { id:'weed',  letters:'-ed',  symbol:'/d/',   emoji:'📕', example:'played',  words:['played','jumped','called'],   speech:'played, jumped, called' },
    { id:'weer',  letters:'-er',  symbol:'/ər/',  emoji:'🌸', example:'butter',  words:['butter','flower','sister'],   speech:'er, er, butter, flower, sister' },
    { id:'weest', letters:'-est', symbol:'/ɪst/', emoji:'🏆', example:'best',    words:['best','rest','chest'],        speech:'est, est, best, rest, chest' },
    { id:'weful', letters:'-ful', symbol:'/fʊl/', emoji:'💛', example:'joyful',  words:['joyful','hopeful','playful'], speech:'ful, ful, joyful, hopeful, playful' },
    { id:'wess',  letters:'-ss',  symbol:'/s/',   emoji:'🐍', example:'miss',    words:['miss','grass','chess'],       speech:'sss, sss, miss, grass, chess' },
    { id:'weall', letters:'all',  symbol:'/ɔːl/', emoji:'🦗', example:'tall',    words:['tall','fall','wall'],          speech:'awl, awl, tall, fall, wall' },
  ],
};

export const TOTAL_SOUNDS = Object.values(SOUNDS).reduce((s, arr) => s + arr.length, 0);

export const ALL_WORDS = [...new Set(
  Object.values(SOUNDS).flatMap(arr => arr.flatMap(s => s.words))
)];
