export const CATEGORIES = [
  { id: 'shortVowels', label: 'Short Vowels', icon: '🔴', color: '#FF6B9D', desc: '5 sounds' },
  { id: 'longVowels',  label: 'Long Vowels',  icon: '🟢', color: '#4ECDC4', desc: '5 sounds' },
  { id: 'consonants',  label: 'Consonants',   icon: '🟣', color: '#A29BFE', desc: '23 sounds' },
  { id: 'digraphs',    label: 'Digraphs',     icon: '🟠', color: '#FD9644', desc: '11 sounds' },
  { id: 'blends',      label: 'Blends',       icon: '🟡', color: '#26DE81', desc: '26 sounds' },
  { id: 'vowelTeams',  label: 'Vowel Teams',  icon: '🔵', color: '#74B9FF', desc: '19 sounds' },
  { id: 'rControlled', label: 'R-Controlled', icon: '🩷', color: '#FD79A8', desc: '5 sounds' },
];

export const SOUNDS = {
  shortVowels: [
    { id: 'sa', letters: 'a', symbol: '/æ/', example: 'apple',   emoji: '🍎', speech: 'aah, aah, apple' },
    { id: 'se', letters: 'e', symbol: '/ɛ/', example: 'egg',     emoji: '🥚', speech: 'eh, eh, egg' },
    { id: 'si', letters: 'i', symbol: '/ɪ/', example: 'igloo',   emoji: '🧊', speech: 'ih, ih, igloo' },
    { id: 'so', letters: 'o', symbol: '/ɒ/', example: 'octopus', emoji: '🐙', speech: 'aw, aw, octopus' },
    { id: 'su', letters: 'u', symbol: '/ʌ/', example: 'umbrella',emoji: '☂️', speech: 'uh, uh, umbrella' },
  ],
  longVowels: [
    { id: 'la', letters: 'ā', symbol: '/eɪ/', example: 'cake',    emoji: '🎂', speech: 'ay, ay, cake' },
    { id: 'le', letters: 'ē', symbol: '/iː/', example: 'eel',     emoji: '🐍', speech: 'ee, ee, eel' },
    { id: 'li', letters: 'ī', symbol: '/aɪ/', example: 'ice',     emoji: '🧊', speech: 'eye, eye, ice' },
    { id: 'lo', letters: 'ō', symbol: '/oʊ/', example: 'open',    emoji: '🚪', speech: 'oh, oh, open' },
    { id: 'lu', letters: 'ū', symbol: '/juː/', example: 'unicorn', emoji: '🦄', speech: 'yoo, yoo, unicorn' },
  ],
  consonants: [
    { id: 'cb', letters: 'b', symbol: '/b/',  example: 'ball',   emoji: '⚽', speech: 'buh, buh, ball' },
    { id: 'cc', letters: 'c', symbol: '/k/',  example: 'cat',    emoji: '🐱', speech: 'kuh, kuh, cat' },
    { id: 'cs', letters: 'c', symbol: '/s/',  example: 'city',   emoji: '🏙️', speech: 'sss, sss, city' },
    { id: 'cd', letters: 'd', symbol: '/d/',  example: 'dog',    emoji: '🐶', speech: 'duh, duh, dog' },
    { id: 'cf', letters: 'f', symbol: '/f/',  example: 'fish',   emoji: '🐟', speech: 'fff, fff, fish' },
    { id: 'cg', letters: 'g', symbol: '/ɡ/',  example: 'goat',   emoji: '🐐', speech: 'guh, guh, goat' },
    { id: 'cgj',letters: 'g', symbol: '/dʒ/', example: 'gem',    emoji: '💎', speech: 'juh, juh, gem' },
    { id: 'ch', letters: 'h', symbol: '/h/',  example: 'hat',    emoji: '🎩', speech: 'huh, huh, hat' },
    { id: 'cj', letters: 'j', symbol: '/dʒ/', example: 'jump',   emoji: '🐸', speech: 'juh, juh, jump' },
    { id: 'ck', letters: 'k', symbol: '/k/',  example: 'kite',   emoji: '🪁', speech: 'kuh, kuh, kite' },
    { id: 'cl', letters: 'l', symbol: '/l/',  example: 'lion',   emoji: '🦁', speech: 'lll, lll, lion' },
    { id: 'cm', letters: 'm', symbol: '/m/',  example: 'moon',   emoji: '🌙', speech: 'mmm, mmm, moon' },
    { id: 'cn', letters: 'n', symbol: '/n/',  example: 'nose',   emoji: '👃', speech: 'nnn, nnn, nose' },
    { id: 'cp', letters: 'p', symbol: '/p/',  example: 'pig',    emoji: '🐷', speech: 'puh, puh, pig' },
    { id: 'cq', letters: 'qu',symbol: '/kw/', example: 'queen',  emoji: '👑', speech: 'kwuh, kwuh, queen' },
    { id: 'cr', letters: 'r', symbol: '/r/',  example: 'rabbit', emoji: '🐰', speech: 'rrr, rrr, rabbit' },
    { id: 'css',letters: 's', symbol: '/s/',  example: 'sun',    emoji: '☀️', speech: 'sss, sss, sun' },
    { id: 'ct', letters: 't', symbol: '/t/',  example: 'tiger',  emoji: '🐯', speech: 'tuh, tuh, tiger' },
    { id: 'cv', letters: 'v', symbol: '/v/',  example: 'van',    emoji: '🚐', speech: 'vvv, vvv, van' },
    { id: 'cw', letters: 'w', symbol: '/w/',  example: 'wolf',   emoji: '🐺', speech: 'wuh, wuh, wolf' },
    { id: 'cx', letters: 'x', symbol: '/ks/', example: 'fox',    emoji: '🦊', speech: 'ks, ks, fox' },
    { id: 'cy', letters: 'y', symbol: '/j/',  example: 'yak',    emoji: '🐃', speech: 'yuh, yuh, yak' },
    { id: 'cz', letters: 'z', symbol: '/z/',  example: 'zebra',  emoji: '🦓', speech: 'zzz, zzz, zebra' },
  ],
  digraphs: [
    { id: 'dch', letters: 'ch', symbol: '/tʃ/', example: 'chair',  emoji: '🪑', speech: 'ch, ch, chair' },
    { id: 'dsh', letters: 'sh', symbol: '/ʃ/',  example: 'ship',   emoji: '🚢', speech: 'shh, shh, ship' },
    { id: 'dthv',letters: 'th', symbol: '/ð/',  example: 'the',    emoji: '📖', speech: 'th, the, the' },
    { id: 'dthu',letters: 'th', symbol: '/θ/',  example: 'think',  emoji: '💭', speech: 'th, th, think' },
    { id: 'dwh', letters: 'wh', symbol: '/w/',  example: 'wheel',  emoji: '🎡', speech: 'wh, wh, wheel' },
    { id: 'dph', letters: 'ph', symbol: '/f/',  example: 'phone',  emoji: '📱', speech: 'fff, fff, phone' },
    { id: 'dgh', letters: 'gh', symbol: '/f/',  example: 'laugh',  emoji: '😂', speech: 'fff, fff, laugh' },
    { id: 'dck', letters: 'ck', symbol: '/k/',  example: 'duck',   emoji: '🦆', speech: 'kuh, kuh, duck' },
    { id: 'dng', letters: 'ng', symbol: '/ŋ/',  example: 'ring',   emoji: '💍', speech: 'ng, ng, ring' },
    { id: 'dkn', letters: 'kn', symbol: '/n/',  example: 'knee',   emoji: '🦵', speech: 'nnn, nnn, knee' },
    { id: 'dwr', letters: 'wr', symbol: '/r/',  example: 'write',  emoji: '✍️', speech: 'rrr, rrr, write' },
  ],
  blends: [
    { id: 'bbl', letters: 'bl', symbol: '/bl/', example: 'blue',   emoji: '💙', speech: 'bl, bl, blue' },
    { id: 'bcl', letters: 'cl', symbol: '/kl/', example: 'clock',  emoji: '🕐', speech: 'cl, cl, clock' },
    { id: 'bfl', letters: 'fl', symbol: '/fl/', example: 'flag',   emoji: '🚩', speech: 'fl, fl, flag' },
    { id: 'bgl', letters: 'gl', symbol: '/ɡl/', example: 'globe',  emoji: '🌍', speech: 'gl, gl, globe' },
    { id: 'bpl', letters: 'pl', symbol: '/pl/', example: 'play',   emoji: '🎮', speech: 'pl, pl, play' },
    { id: 'bsl', letters: 'sl', symbol: '/sl/', example: 'slide',  emoji: '🛝', speech: 'sl, sl, slide' },
    { id: 'bbr', letters: 'br', symbol: '/br/', example: 'bread',  emoji: '🍞', speech: 'br, br, bread' },
    { id: 'bcr', letters: 'cr', symbol: '/kr/', example: 'crab',   emoji: '🦀', speech: 'cr, cr, crab' },
    { id: 'bdr', letters: 'dr', symbol: '/dr/', example: 'drum',   emoji: '🥁', speech: 'dr, dr, drum' },
    { id: 'bfr', letters: 'fr', symbol: '/fr/', example: 'frog',   emoji: '🐸', speech: 'fr, fr, frog' },
    { id: 'bgr', letters: 'gr', symbol: '/ɡr/', example: 'grape',  emoji: '🍇', speech: 'gr, gr, grape' },
    { id: 'bpr', letters: 'pr', symbol: '/pr/', example: 'prince', emoji: '🤴', speech: 'pr, pr, prince' },
    { id: 'btr', letters: 'tr', symbol: '/tr/', example: 'tree',   emoji: '🌳', speech: 'tr, tr, tree' },
    { id: 'bsc', letters: 'sc', symbol: '/sk/', example: 'scarf',  emoji: '🧣', speech: 'sc, sc, scarf' },
    { id: 'bsk', letters: 'sk', symbol: '/sk/', example: 'skate',  emoji: '⛸️', speech: 'sk, sk, skate' },
    { id: 'bsm', letters: 'sm', symbol: '/sm/', example: 'smile',  emoji: '😊', speech: 'sm, sm, smile' },
    { id: 'bsn', letters: 'sn', symbol: '/sn/', example: 'snake',  emoji: '🐍', speech: 'sn, sn, snake' },
    { id: 'bsp', letters: 'sp', symbol: '/sp/', example: 'spider', emoji: '🕷️', speech: 'sp, sp, spider' },
    { id: 'bst', letters: 'st', symbol: '/st/', example: 'star',   emoji: '⭐', speech: 'st, st, star' },
    { id: 'bsw', letters: 'sw', symbol: '/sw/', example: 'swan',   emoji: '🦢', speech: 'sw, sw, swan' },
    { id: 'bstr',letters: 'str',symbol: '/str/',example: 'string', emoji: '🎻', speech: 'str, str, string' },
    { id: 'bspr',letters: 'spr',symbol: '/spr/',example: 'spring', emoji: '🌸', speech: 'spr, spr, spring' },
    { id: 'bscr',letters: 'scr',symbol: '/skr/',example: 'scream', emoji: '😱', speech: 'scr, scr, scream' },
    { id: 'bspl',letters: 'spl',symbol: '/spl/',example: 'splash', emoji: '💦', speech: 'spl, spl, splash' },
    { id: 'bsqu',letters: 'squ',symbol: '/skw/',example: 'square', emoji: '🟥', speech: 'squ, squ, square' },
    { id: 'bthr',letters: 'thr',symbol: '/θr/', example: 'three',  emoji: '3️⃣', speech: 'thr, thr, three' },
  ],
  vowelTeams: [
    { id: 'vai', letters: 'ai', symbol: '/eɪ/', example: 'rain',  emoji: '🌧️', speech: 'ay, ay, rain' },
    { id: 'vay', letters: 'ay', symbol: '/eɪ/', example: 'play',  emoji: '🎮', speech: 'ay, ay, play' },
    { id: 'vea', letters: 'ea', symbol: '/iː/', example: 'eat',   emoji: '🍽️', speech: 'ee, ee, eat' },
    { id: 'vee', letters: 'ee', symbol: '/iː/', example: 'tree',  emoji: '🌳', speech: 'ee, ee, tree' },
    { id: 'vie', letters: 'ie', symbol: '/aɪ/', example: 'pie',   emoji: '🥧', speech: 'eye, eye, pie' },
    { id: 'voa', letters: 'oa', symbol: '/oʊ/', example: 'boat',  emoji: '⛵', speech: 'oh, oh, boat' },
    { id: 'voe', letters: 'oe', symbol: '/oʊ/', example: 'toe',   emoji: '🦶', speech: 'oh, oh, toe' },
    { id: 'vool',letters: 'oo', symbol: '/uː/', example: 'moon',  emoji: '🌙', speech: 'oo, oo, moon' },
    { id: 'voos',letters: 'oo', symbol: '/ʊ/',  example: 'book',  emoji: '📚', speech: 'oo short, oo short, book' },
    { id: 'vou', letters: 'ou', symbol: '/aʊ/', example: 'cloud', emoji: '☁️', speech: 'ow, ow, cloud' },
    { id: 'vowd',letters: 'ow', symbol: '/aʊ/', example: 'cow',   emoji: '🐄', speech: 'ow, ow, cow' },
    { id: 'vowl',letters: 'ow', symbol: '/oʊ/', example: 'snow',  emoji: '❄️', speech: 'oh, oh, snow' },
    { id: 'voi', letters: 'oi', symbol: '/ɔɪ/', example: 'coin',  emoji: '🪙', speech: 'oy, oy, coin' },
    { id: 'voy', letters: 'oy', symbol: '/ɔɪ/', example: 'boy',   emoji: '👦', speech: 'oy, oy, boy' },
    { id: 'vau', letters: 'au', symbol: '/ɔː/', example: 'haul',  emoji: '🏋️', speech: 'aw, aw, haul' },
    { id: 'vaw', letters: 'aw', symbol: '/ɔː/', example: 'saw',   emoji: '🪚', speech: 'aw, aw, saw' },
    { id: 'vew', letters: 'ew', symbol: '/juː/',example: 'new',   emoji: '✨', speech: 'yoo, yoo, new' },
    { id: 'vue', letters: 'ue', symbol: '/uː/', example: 'blue',  emoji: '💙', speech: 'oo, oo, blue' },
    { id: 'vui', letters: 'ui', symbol: '/uː/', example: 'fruit', emoji: '🍓', speech: 'oo, oo, fruit' },
  ],
  rControlled: [
    { id: 'rar', letters: 'ar', symbol: '/ɑːr/', example: 'car',  emoji: '🚗', speech: 'ar, ar, car' },
    { id: 'rer', letters: 'er', symbol: '/ɜːr/', example: 'her',  emoji: '👩', speech: 'er, er, her' },
    { id: 'rir', letters: 'ir', symbol: '/ɜːr/', example: 'bird', emoji: '🐦', speech: 'er, er, bird' },
    { id: 'ror', letters: 'or', symbol: '/ɔːr/', example: 'corn', emoji: '🌽', speech: 'or, or, corn' },
    { id: 'rur', letters: 'ur', symbol: '/ɜːr/', example: 'burn', emoji: '🔥', speech: 'er, er, burn' },
  ],
};

export const TOTAL_SOUNDS = Object.values(SOUNDS).reduce((s, arr) => s + arr.length, 0);
